#version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ab147890
      MYSQL_DATABASE: eshop
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: my-redis
    networks:
      - app-network

  eshoping-api:
    image: 'eshoping-api'
    volumes:
      - type: bind
        source: ./config
        target: /app/config
    ports:
      - 8889:8889
    depends_on:
      - mysql
      - redis
#      - zookeeper
      - etcd
      - kafka
    networks:
      - app-network

  eshoping-user:
    image: 'eshoping-user'
    environment:
      - ETCD_PASSWORD=ab147890
    volumes:
      - type: bind
        source: ./config
        target: /app/config
    ports:
      - 8888:8888
    depends_on:
      - eshoping-api
      - mysql
      - redis
#      - zookeeper
      - etcd
      - kafka
    networks:
      - app-network

  eshoping-product:
    image: 'eshoping-product'
    environment:
      - ETCD_PASSWORD=ab147890
    volumes:
      - type: bind
        source: ./config
        target: /app/config
    ports:
      - 8887:8887
    depends_on:
      - eshoping-api
      - mysql
      - redis
#      - zookeeper
      - etcd
      - kafka
    networks:
      - app-network

  eshoping-order:
    image: 'eshoping-order'
    environment:
      - ETCD_PASSWORD=ab147890
    volumes:
      - type: bind
        source: ./config
        target: /app/config
    ports:
      - 8885:8885
    depends_on:
      - eshoping-api
      - mysql
      - redis
#      - zookeeper
      - etcd
      - kafka
    networks:
      - app-network

  etcd:
    image: 'bitnami/etcd:latest'
    container_name: my-etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - app-network

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: my-kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://172.30.48.1:9093
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - ./kafka_data:/var/lib/kafka/data
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local
  consul-data:
    driver: local
  kafka_data:
    driver: local

networks:
  app-network:
    driver: bridge

