mysql:
  source: # 主数据库
    driverName: mysql
    host: my-mysql
    port: 3309
    database: eshop
    username: root
    password: ab147890
    charset: utf8mb4
redis:
  addr: my-redis
  port: 6379
  password:
  db: 0 # 数据库编号